AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Plantilla CloudFormation para crear una base de datos RDS MySQL.
    Utiliza los datos de la VPC y subredes creadas en la pila anterior. Con !ImportValue
            - 1 instancia EC2 Ubuntu Server 24.04 bastión con IPv4 elastica
            - 1 instancia RDS MySQL 8.0
            - 1 zona privada en Route53
            - 1 grupo de seguridad para la base de datos
            - 1 grupo de seguridad para el bastión Ubuntu
            - 1 grupo de subredes para la base de datos
            - 1 registro DNS en la zona privada para la base de datos
    Autor: Javier Teran Gonzalez
    Fecha creacion:     18/02/2025
    Version: 1.20
Parameters:
    AMIUbuntu:
        Description: AMI ID Ubuntu Server 24.04.
        Type: String
        Default: 'ami-04b4f1a9cf54c11d0'    
Resources:
  MiDDBBsg:
      Type: 'AWS::EC2::SecurityGroup'
      Properties: 
        GroupName: !Join [ '', [!ImportValue Proyecto, '-bbdd-sg']]
        GroupDescription: 'MiDDBBsg. Habilitar el acceso a la base de datos MySQL'
        VpcId: !ImportValue MiVPCID        # Referencia al VPC donde estará la base de datos
        SecurityGroupIngress: 
          - IpProtocol: 'tcp'
            FromPort: '3306'
            ToPort: '3306'
            SourceSecurityGroupId: !ImportValue MisDestinosSGID  # Referencia al grupo de seguridad de Ubuntus Destinos
            Description: Permitir trafico desde el grupo de seguridad de los Ubuntus Balanceados  
          - IpProtocol: 'tcp'
            FromPort: '3306'
            ToPort: '3306'
            #SourceSecurityGroupId: !ImportValue MiBastionSGID  # Referencia al grupo de seguridad de Ubuntu Bastion
            SourceSecurityGroupId: !Ref UbuntuBastionSecurityGroup  # Referencia al grupo de seguridad de Ubuntu Bastion
            Description: Permitir trafico desde el grupo de seguridad del ubuntu bastion
        Tags:
            - Key: Name
              Value: !Join [ '', [!ImportValue Proyecto, '-bbdd-sg']]
  MiGrupoSubredesDB:
      Type: 'AWS::RDS::DBSubnetGroup'
      Properties:
        DBSubnetGroupDescription: 'Grupo de subredes para la base de datos MySQL'
        SubnetIds: 
          - !ImportValue MiSubredPrivada1ID # Subred privada1 de la VPC
          - !ImportValue MiSubredPrivada2ID # Subred privada2 de la VPC
          - !ImportValue MiSubredPrivada3ID # Subred privada3 de la VPC

  MiInstanciaBBDD:
      Type: 'AWS::RDS::DBInstance'
      Properties: 
        #DBInstanceIdentifier: !ImportValue '${Proyecto}-bbdd'    # Nombre de la instancia de la base de datos
        DBInstanceIdentifier:  !Join [ '', [!ImportValue Proyecto, '-bbdd']]   # Nombre de la instancia de la base de datos
        DBInstanceClass: 'db.t3.micro'        # Clase de instancia de la base de datos (db.t3.micro es adecuada para pruebas)
        AllocatedStorage: '20'                # Almacenamiento en GB
        DBName: MiBaseDatos                   # Nombre de la base de datos
        Engine: MySQL                         # Motor de base de datos (en este caso MySQL)
        EngineVersion: '8.0'                  # Versión de MySQL
        MasterUsername: 'admin'               # Usuario administrador
        MasterUserPassword: 'admin12345'      # Contraseña del administrador (modifica para producción)
        BackupRetentionPeriod: 7              # Número de días que se retendrán los backups automáticos
        MultiAZ: False                        # Si es una instancia Multi-AZ o no
        PubliclyAccessible: False             # Define si la base de datos es accesible públicamente
        StorageType: 'gp2'                    # Tipo de almacenamiento (gp2 es almacenamiento en discos SSD)
        VPCSecurityGroups: 
          - !Ref MiDDBBsg                     # Referencia al grupo de seguridad de la base de datos
        DBSubnetGroupName: !Ref MiGrupoSubredesDB  # Subnet group de la base de datos

  # Grupo de seguridad Ubuntu. Puertos DNS, HTTP, HTTPS y SSH
  UbuntuBastionSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          #GroupName: !Sub '${NombreProyecto}${NN}-usbastion-sg'
          #GroupDescription: !Sub '${NombreProyecto}${NN}-usbastion-sg'
          GroupName:  !Join [ '', [!ImportValue Proyecto, '-usbastion-sg']]
          GroupDescription: !Join [ '', [!ImportValue Proyecto, '-usbastion-sg']]

          #VpcId: !Ref VPC
          VpcId: !ImportValue MiVPCID  
          SecurityGroupIngress:           
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
              Description: Permitir SSH IPv4            
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIpv6: ::/0
              Description: Permitir SSH IPv6
          Tags:
              - Key: Name
#                Value: !Sub '${NombreProyecto}${NN}-usbastion-sg'
                Value: !Join [ '', [!ImportValue Proyecto, '-usbastion-sg']]
  # Creacion de instancia Ubuntu
  UbuntuBastion:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: !Ref AMIUbuntu
        InstanceType: t2.micro
        KeyName: vockey
        Monitoring: false
#        SecurityGroupIds:
#            - !Ref UbuntuBastionSecurityGroup
        #SubnetId: !Ref SubredPublica1
#        SubnetId: !ImportValue MiSubredPublica1ID # Subred publica1 de la VPC
        NetworkInterfaces:
            - DeviceIndex: 0
              AssociatePublicIpAddress: true
              SubnetId: !ImportValue MiSubredPublica1ID # Subred publica1 de la VPC
              GroupSet: 
                  - !Ref UbuntuBastionSecurityGroup

        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo 'User data para Ubuntu Server Bastion. Creará la base de datos MySQL y meterá datos de prueba'
            apt-get update -y
            apt-get upgrade -y
            apt-get install mysql-client -y
            mysql -h ${MiInstanciaBBDD.Endpoint.Address} -u admin -padmin12345 MiBaseDatos << EOF
                DROP TABLE IF EXISTS Clientes;
                CREATE TABLE Clientes 
                    (id                        VARCHAR(3)  NOT NULL,
                    name                       VARCHAR(20) NOT NULL,
                    phone                      VARCHAR(20) NOT NULL,
                    address                    VARCHAR(20),
                    city                       VARCHAR(20),
                    state                      VARCHAR(15),
                    country                    VARCHAR(20),
                    zip_code                   VARCHAR(15),
                    credit_rating              VARCHAR(9),
                    sales_rep_id               VARCHAR(3),
                    region_id                  VARCHAR(3),
                    comments                   VARCHAR(255),
                    CONSTRAINT Clientes_id_pk PRIMARY KEY (id),
                    CONSTRAINT Clientes_credit_rating_ck
                    CHECK (credit_rating IN ('EXCELENTE', 'BUENO', 'POBRE'))
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

                INSERT INTO Clientes VALUES ('301', 'Sports,Inc', '540-123-4567','72 High St','Harrisonburg', 'VA','US', '22809','EXCELENTE', '12', '1', NULL);
                INSERT INTO Clientes VALUES ('302', 'Toms Sporting BUENOs', '540-987-6543','6741 Main St','Harrisonburg', 'VA','US', '22809','POBRE', '14', '1', NULL);
                INSERT INTO Clientes VALUES ('303', 'Athletic Attire', '540-123-6789','54 Market St','Harrisonburg', 'VA','US', '22808','BUENO', '14', '1', NULL);
                INSERT INTO Clientes VALUES ('304', 'Athletics For All', '540-987-1234','286 Main St', 'Harrisonburg', 'VA', 'US', '22808','EXCELENTE', '12', '1', NULL);
                INSERT INTO Clientes VALUES ('305', 'Shoes for Sports', '540-123-9876','538 High St', 'Harrisonburg', 'VA','US', '22809','EXCELENTE', '14', '1', NULL);
                INSERT INTO Clientes VALUES ('306', 'BJ Athletics', '540-987-9999','632 Water St', 'Harrisonburg', 'VA','US', '22810','POBRE', '12', '1', NULL);
                INSERT INTO Clientes VALUES ('403', 'Athletics One', '717-234-6786','912 Columbia Rd', 'Lancaster', 'PA','US', '17601','BUENO', '14', '1', NULL);
                INSERT INTO Clientes VALUES ('404', 'Great Athletes', '717-987-2341','121 Litiz Pike', 'Lancaster', 'PA','US', '17602','EXCELENTE', '12', '1', NULL);
                INSERT INTO Clientes VALUES ('405', 'Athletics Two', '717-987-9875','435 High Rd', 'Lancaster', 'PA','US', '17602','EXCELENTE', '14', '1', NULL);
                INSERT INTO Clientes VALUES ('406', 'Athletes Attic', '717-234-9888','101 Greenfield Rd','Lancaster', 'PA','US', '17601','POBRE', '12', '1', NULL);
                INSERT INTO Clientes VALUES ('201', 'One Sport', '55-112066222','82 Via Bahia', 'Sao Paolo', NULL, 'Brazil', NULL,'EXCELENTE', '12', '2', NULL);
                INSERT INTO Clientes VALUES ('202', 'Deportivo Caracas', '58-28066222','31 Sabana Grande', 'Caracas', NULL, 'Venezuela', NULL,'EXCELENTE', '12', '2', NULL);
                INSERT INTO Clientes VALUES ('203', 'New Delhi Sports', '91-11903338','11368 Chanakya', 'New Delhi', NULL, 'India', NULL,'BUENO', '11', '4', NULL);
                INSERT INTO Clientes VALUES ('204', 'Ladysport', '1-206-104-0111','281 Queen Street', 'Seattle', 'Washington', 'US', NULL,'EXCELENTE', '11', '1', NULL);
                INSERT INTO Clientes VALUES ('205', 'Kim''s Sporting BUENOs', '852-3693888','15 Henessey Road','Hong Kong', NULL, NULL, NULL,'EXCELENTE', '11', '4', NULL);
                INSERT INTO Clientes VALUES ('206', 'Sportique', '33-93425722253','172 Rue de Place', 'Cannes', NULL, 'France', NULL,'EXCELENTE', '13', '5', NULL);
                INSERT INTO Clientes VALUES ('207', 'Tall Rock Sports', '234-16036222','10 Saint Antoine','Lagos', NULL, 'Nigeria', NULL,'BUENO', NULL, '3', NULL);
                INSERT INTO Clientes VALUES ('208', 'Muench Sports', '49-895274449','435 Gruenestrasse','Munich', NULL, 'Germany', NULL,'BUENO', '13', '5', NULL);
                INSERT INTO Clientes VALUES ('209', 'Beisbol Si!', '809-352666','415 Playa Del Mar', 'San Pedro', NULL, 'Dominican Republic', NULL,'EXCELENTE','11','6', NULL);
                INSERT INTO Clientes VALUES ('210', 'Futbol Sonora', '52-404555','5 Via Saguaro', 'Nogales', NULL, 'Mexico', NULL,'EXCELENTE', '12', '2', NULL);
                INSERT INTO Clientes VALUES ('211', 'Helmut''s Sports', '42-2111222','45 Modrany', 'Prague', NULL, 'Czechoslovakia', NULL,'EXCELENTE', '11', '5', NULL);
                INSERT INTO Clientes VALUES ('213', 'Sports Emporium', '1-415-555-6281','4783 168th Street', 'San Francisco', 'CA', 'US', NULL,'EXCELENTE', '11', '1', NULL);
                INSERT INTO Clientes VALUES ('214', 'Sports Retail', '1-716-555-7777','115 Main Street','Buffalo', 'NY', 'US', NULL, 'POBRE', '11', '1', NULL);
                INSERT INTO Clientes VALUES ('215', 'Sports Russia', '7-0953892444','7070 Yekatamina', 'Saint Petersburg', NULL, 'Russia', NULL,'POBRE', '11', '5', NULL);

                CREATE TABLE IF NOT EXISTS Personas (
                  IdPersona   int(11)     NOT NULL,
                  Nombre      varchar(40) NOT NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

                INSERT INTO Personas (IdPersona, Nombre) VALUES (1, 'Javier'),(2, 'Juan'),(3, 'Pedro'),(4, 'Maria'),(5, 'Ana');

                CREATE TABLE Alumnos (
                  IdAlumno        int(11)     NOT NULL,
                  Apellidos       varchar(18) DEFAULT NULL,
                  Nombre          varchar(13) DEFAULT NULL,
                  Sexo            varchar(1) DEFAULT NULL,
                  Foto            varchar(10) DEFAULT NULL,
                  DireccionA      varchar(28) DEFAULT NULL,
                  LocalidadA      varchar(22) DEFAULT NULL,
                  ProvinciaA      varchar(10) DEFAULT NULL,
                  CodPostalA      int DEFAULT NULL,
                  TelefonoA       int DEFAULT NULL,
                  TutorContacto   varchar(26) DEFAULT NULL,
                  FechaNacimientoA varchar(10) DEFAULT NULL,
                  CorreoA         varchar(35) DEFAULT NULL,
                  PcorreoA        varchar(10) DEFAULT NULL,
                  WebA            varchar(30) DEFAULT NULL,
                  PWebA           varchar(10) DEFAULT NULL,
                  TelefonoA2      int DEFAULT NULL,
                  CorreoEmpresarial varchar(35) DEFAULT NULL,
                  CONSTRAINT pk_Alumnos PRIMARY KEY (IdAlumno)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

                -- Volcado de datos para la tabla 'Alumnos'
                INSERT INTO Alumnos  VALUES
                (2000, 'Wiz', 'Prince', 'M', '', '788 Macpherson Place', 'Limpias', '', 32260, 697724216, 'Prince Wiz', '29/12/1988', 'pwiz0@behance.net', '', 'http://comsenz.com', '', 667220555, 'pwiz0@wiley.com');
                INSERT INTO Alumnos VALUES
                (1, 'Wiz', 'Prince', 'M', '', '788 Macpherson Place', 'Limpias', '', 32260, 697724216, 'Prince Wiz', '29/12/1988', 'pwiz0@behance.net', '', 'http://comsenz.com', '', 667220555, 'pwiz0@wiley.com'),
                (2, 'Kharchinski', 'Calv', 'M', '', '3506 Birchwood Pass', 'Laredo', '', 37564, 686166496, 'Calv Kharchinski', '22/06/1974', 'ckharchinski1@bing.com', '', 'https://vkontakte.ru', '', 686157565, 'ckharchinski1@spotify.com'),
                (3, 'Hawney', 'Codie', 'M', '', '20963 Kipling Terrace', 'Entrambasaguas', '', 36450, 679075330, 'Codie Hawney', '17/03/1979', 'chawney2@microsoft.com', '', 'https://patch.com', '', 695457845, 'chawney2@engadget.com'),
                (4, 'Chattington', 'Delaney', 'M', '', '2734 Hudson Circle', 'Torrelavega', '', 31570, 657002162, 'Delaney Chattington', '21/07/1969', 'dchattington3@blinklist.com', '', 'http://sina.com.cn', '', 685416744, 'dchattington3@independent.co.uk'),
                (5, 'Grundey', 'Ossie', 'M', '', '1377 Cascade Point', 'Madrid', '', 37819, 695196237, 'Ossie Grundey', '26/03/1962', 'ogrundey4@hao123.com', '', 'http://fastcompany.com', '', 628195725, 'ogrundey4@yahoo.co.jp'),
                (6, 'Riddler', 'Redd', 'M', '', '45811 Anderson Lane', 'Arnedo', '', 33184, 686592318, 'Redd Riddler', '13/03/1981', 'rriddler5@arstechnica.com', '', 'http://nps.gov', '', 654383618, 'rriddler5@examiner.com'),
                (7, 'Durban', 'Gratia', 'F', '', '14 Darwin Lane', 'Llermo', '', 31396, 629450239, 'Gratia Durban', '12/03/1986', 'gdurban6@mayoclinic.com', '', 'https://flavors.me', '', 650521007, 'gdurban6@vistaprint.com'),
                (8, 'Tolomio', 'Jade', 'F', '', '245 Delaware Crossing', 'Camargo', '', 33745, 649396549, 'Jade Tolomio', '23/04/1996', 'jtolomio7@shutterfly.com', '', 'https://alibaba.com', '', 674108895, 'jtolomio7@discovery.com'),
                (9, 'Suckling', 'Elita', 'F', '', '1402 Ruskin Plaza', 'Burgos', '', 35821, 630243519, 'Elita Suckling', '03/02/1970', 'esuckling8@alibaba.com', '', 'http://flickr.com', '', 673831424, 'esuckling8@bravesites.com'),
                (10, 'Webben', 'Reynolds', 'M', '', '36102 Vahlen Circle', 'Boo de Pielagos', '', 32175, 648642601, 'Reynolds Webben', '03/11/1978', 'rwebben9@dion.ne.jp', '', 'http://geocities.com', '', 689740929, 'rwebben9@skyrock.com'),
                (11, 'Langdon', 'Saloma', 'F', '', '57 Farragut Drive', 'Entrambasaguas', '', 39235, 674335215, 'Saloma Langdon', '14/11/1980', 'slangdona@twitter.com', '', 'http://wix.com', '', 647314510, 'slangdona@chron.com'),
                (12, 'Torbet', 'Dennis', 'M', '', '36341 Roth Pass', 'Guriezo', '', 36758, 619416594, 'Dennis Torbet', '27/09/1982', 'dtorbetb@usnews.com', '', 'http://timesonline.co.uk', '', 618607129, 'dtorbetb@macromedia.com'),
                (13, 'Donnellan', 'Eugenie', 'F', '', '114 Katie Road', 'Torrelavega', '', 39346, 664245088, 'Eugenie Donnellan', '17/06/1975', 'edonnellanc@chron.com', '', 'http://mediafire.com', '', 665234182, 'edonnellanc@sciencedirect.com'),
                (14, 'Wythe', 'Caresa', 'F', '', '3066 Sage Terrace', 'Ribamontan al Mar', '', 38370, 601431597, 'Caresa Wythe', '30/08/1960', 'cwythed@twitter.com', '', 'http://cmu.edu', '', 685419334, 'cwythed@desdev.cn'),
                (15, 'Jarratt', 'Ardelia', 'F', '', '9941 Hanover Junction', 'Santiago de Cartes', '', 36471, 632407280, 'Ardelia Jarratt', '08/07/1990', 'ajarratte@reverbnation.com', '', 'http://cocolog-nifty.com', '', 679209520, 'ajarratte@google.nl'),
                (16, 'Gascar', 'Celinda', 'F', '', '675 Morningstar Drive', 'Ribamontan al Mar', '', 39608, 620567261, 'Celinda Gascar', '18/05/1968', 'cgascarf@washington.edu', '', 'http://google.it', '', 617533594, 'cgascarf@deviantart.com'),
                (17, 'Pea', 'Tucker', 'M', '', '9 Armistice Center', 'El Astillero', '', 36781, 688428595, 'Tucker Pea', '07/09/1989', 'tpeag@pcworld.com', '', 'https://vistaprint.com', '', 683212137, 'tpeag@chicagotribune.com'),
                (18, 'Godsmark', 'Meredith', 'F', '', '750 Division Drive', 'Cabezon de la Sal', '', 31409, 667697513, 'Meredith Godsmark', '01/03/1970', 'mgodsmarkh@w3.org', '', 'http://google.com.hk', '', 657534652, 'mgodsmarkh@seattletimes.com'),
                (19, 'Charle', 'Ernst', 'M', '', '4 Londonderry Circle', 'Cartes', '', 33145, 684253218, 'Ernst Charle', '24/10/1989', 'echarlei@sbwire.com', '', 'https://cyberchimps.com', '', 680957171, 'echarlei@histats.com');
            EOF
        Tags:
          - Key: Name
            #Value: !Sub '${NombreProyecto}${NN}-us-bastion'
            Value: !Join [ '', [!ImportValue Proyecto, '-usbastion']]
        BlockDeviceMappings:
          - DeviceName: /dev/sda1  # El volumen raíz de la instancia
            Ebs:
              VolumeSize: 20  # Tamaño del volumen en GB
              VolumeType: gp3  # Tipo de volumen
              DeleteOnTermination: true  # El volumen se eliminará cuando la instancia termine
  UbuntuElasticIp:
      Type: AWS::EC2::EIP
      Properties:
          InstanceId: !Ref UbuntuBastion
          Tags:
              - Key: Name
                #Value: !Sub '${NombreProyecto}${NN}-us-ip'
                Value: !Join [ '', [!ImportValue Proyecto, '-usbastion-ip']]

  MiRecordSetBastion:
#      DependsOn: UbuntuBastion
      DependsOn: UbuntuElasticIp
      Type: AWS::Route53::RecordSet
      Properties:
#          HostedZoneId: !Ref MiZonaPrivadaHosteada
#          Name: !Sub 'bastion.${NombreProyecto}${NN}.es'
          HostedZoneId: !ImportValue MiZonaDNSPrivada
          Name: !Join [ '', ['bastion.',!ImportValue Proyecto, '.es']]
          Type: A
          TTL: '60'
          ResourceRecords:
              - !GetAtt UbuntuBastion.PublicIp
  MyRecordSetRDS:
      Type: AWS::Route53::RecordSet
      Properties:
          HostedZoneId: !ImportValue MiZonaDNSPrivada
          Name: !Join [ '', ['rds.',!ImportValue Proyecto, '.es']]
          Type: CNAME
          TTL: '60'
          ResourceRecords:
              - !GetAtt MiInstanciaBBDD.Endpoint.Address

Outputs:
  DBInstanceEndpoint:
    Description: 'Endpoint/DNS de la base de datosMySQL'
    Value: !GetAtt MiInstanciaBBDD.Endpoint.Address
  UbuntuBastionIPv4Publica:
      Description: Ubuntu Bastion IPv4 publica
      Value: !GetAtt UbuntuBastion.PublicIp
  #UbuntuBastionIPv4Publica:
  #    Description: Ubuntu Bastion IPv6 publica
  #    Value: !Select [0, !GetAtt UbuntuBastion.Ipv6Addresses]
  #    Value: !GetAtt MyInstance.NetworkInterfaces[0].Ipv6Addresses